### ISSUE TITLE
httpClient.Do: couldn't find DNS entries for the given domain. Try using DialDualStack

### ISSUE THREAD

**Issue by erkexzcx** [erkexzcx/stoppropaganda#100]
Shown as running (should be paused instead?)
```json
        "http://mcspro.ru": {
            "requests": 1222,
            "errors": 1222,
            "last_error_msg": "httpClient.Do: couldn't find DNS entries for the given domain. Try using DialDualStack",
            "status": "Running",
            "status_100": 0,
            "status_200": 0,
            "status_300": 0,
            "status_400": 0,
            "status_500": 0
        },
```

**Comment by deputinizer** [comment]
Weird, i still don't understand why fasthttp DNS resolves differently to yours `GetIPs`

**Comment by deputinizer** [comment]
Since we now fetch first from Yandex DNS,
`couldn't find DNS entries for the given domain.` shouldn't happen.
Btw, check http://127.0.0.1:8049/dnscache (almost everything resolves properly)

**Comment by deputinizer** [comment]
My poor comparison:
`stoppropaganda_v0.0.36_linux_x86_64`
minimum: `rx:    42.51 Mbit/s  4116 p/s          tx:     1.50 Mbit/s  1963 p/s`
maximum: `rx:   130.02 Mbit/s 11818 p/s          tx:     3.39 Mbit/s  4654 p/s`
CPU: 30-60% 
MEM: 420MB

`stoppropaganda_v0.0.29_linux_x86_64`
minimum: `rx:    13.34 Mbit/s  2425 p/s          tx:     2.78 Mbit/s  2555 p/s`
maximum: `rx:    39.35 Mbit/s  6161 p/s          tx:     6.57 Mbit/s  5654 p/s`
CPU: 50-90%
MEM: 822MB

**Comment by erkexzcx** [comment]
Let's close this issue then.
