### ISSUE TITLE
Dynamic load of targets + override target IP

### ISSUE THREAD

**Issue by juozukas1** [erkexzcx/stoppropaganda#104]
Hello. 

1) Want to be able to dynamically load a list of targets. Thinking that current way that is compiled in code is not efficient. Things change quickly, some people want to add more or remove some (to have more targeted load, or remove ones they are not comfortable with). We could have the current 'default' list and be able to override it via command line/env variables with a file perhaps. 

2) Want to be able to directly target IPs after target.

Thought about just doing docker/ docker-compose bind, load targets from file & load /etc/hosts from file.
This does not then allow all the other deployment ways to load properly. (IPs are very well known in telegram, etc. We do not have a smart capability to hit site header with target IP (cloudflare, etc).. We could also update the list often here so people who need more help can utilize the tool. 

Saw some example code here  https://github.com/erkexzcx/stoppropaganda/issues/45#issuecomment-1057286841 
Maybe would be able to make this dynamic. 

Very short on time lately, sorry. Need to write this this today or please maybe others can.
Will raise PR ASAP. Let me know if this makes sense.

**Comment by erkexzcx** [comment]
There are few reasons why I am against this:
- Use centralized and remote targets list (e.g. in this repo, TXT file) would make it a killswitch. If I remove it - DOS stops. I don't want to implement killswitch. It's bad approach.
- Managing configuration file is additional hassle for some users, therefore I've made it harder for me, but easier to them.
- Are those targets that have HTTP/HTTPS/DNS services and you want to DOS them?

**Comment by juozukas1** [comment]
1) We already have https://github.com/erkexzcx/stoppropaganda/blob/main/internal/targets/websites.go#L5 . Sorry not sure how killswitch term is understood in this context, can you please elaborate.

2) I understand what you mean. I am very grateful of the simplicity of this tool. 
Therefore wrote that "We could have the current 'default' list and be able to override it via command line/env variables with a file perhaps.". This is currently implemented by 1). 
The idea would be - perhaps - for more advanced users to overwrite the file list on demand (telegram, etc.) to focus attacks. The current approach is too broad for advanced use. This approach doesn't change anything for novice users. 

3) The current website mostly started just hitting  Cloudflare and makes little impact. The idea would be to target web servers in the backend, circumventing Cloudflare. Therefore we need a map of websites/IPs rather than resolve them directly. 

As a whole: 1) for more advanced users allow overwrite  website list by file - changes nothing for novice users.
2) for both novice users and advanced users make/upkeep/create capability to circumvent such systems as Cloudflare and hit backend directly. (Most websites just recently activated cloudflare and there are many tools to track previous IPs).

For example:

```
92.61.37.66 viada.lt
92.61.37.66 loyalty.lt
92.61.37.66 cards.viada.lt
```

**Comment by juozukas1** [comment]
Will make example first.

**Comment by erkexzcx** [comment]
> Sorry not sure how killswitch term is understood in this context, can you please elaborate.

Basically once there is centralised list of targets and when all the applications pull that centralised list on startup (or in regular intervals) - removing this list or modifying (e.g. making it empty) will result in complete (D)DOS shutdown. I will never do it and it's a bad practice.

Example in real life: https://www.forbes.com/sites/leemathews/2021/08/27/samsung-reveals-kill-switch-that-can-remotely-disable-stolen-tvs/

And lastly, I don't want to be the one who can remotely disable all the stoppropaganda instances:)

**Comment by deputinizer** [comment]
Bypass made in https://github.com/erkexzcx/stoppropaganda/pull/108 btw
