### ISSUE TITLE
Question re. DNS resolver

### ISSUE THREAD

**Issue by FluxState** [erkexzcx/stoppropaganda#107]
Do system settings still need to point to Russian DNSes or is it fully handled by the [built-in resolver](https://github.com/erkexzcx/stoppropaganda/blob/main/internal/customresolver/customresolver.go) now?

**Comment by erkexzcx** [comment]
I would say - no.

**Comment by deputinizer** [comment]
> is it fully handled by the [built-in resolver](https://github.com/erkexzcx/stoppropaganda/blob/main/internal/customresolver/customresolver.go) now?

Yes, everything goes through built-in resolver. Yandex DNS returns all the domains properly.
