### ISSUE TITLE
Windows Defender at it's finest

### ISSUE THREAD

**Issue by erkexzcx** [erkexzcx/stoppropaganda#127]
![image](https://user-images.githubusercontent.com/5955795/157537076-e6e1496d-3eac-4dd6-a6ec-2e2c08620e7f.png)

Looks like quite a lot of info about "False positives" on Google if you search for `:Win32/Wacatac.B!ml`.

You can also build yourself if you don't trust my binaries: https://github.com/erkexzcx/stoppropaganda/blob/main/build.sh

**Comment by deputinizer** [comment]
Lol. The first thing to do on Windows if you're a developer is to disable "Realtime protection" and "Send samples to Microsoft"

**Comment by deputinizer** [comment]
Btw `build.sh` has some weird `\r` or CRLF characters.
I can't `bash build.sh`, only `./build.sh` works :disappointed:

**Comment by deputinizer** [comment]
https://github.com/golang/go/issues/44351

**Comment by erkexzcx** [comment]
https://github.com/erkexzcx/stoppropaganda/commit/2273cd193457558cc2620a1aefe231d9f42c2216
