### ISSUE TITLE
Thank me later 🤣

### ISSUE THREAD

**Issue by Russianspy-exe** [erkexzcx/stoppropaganda#128]
https://www.virustotal.com/gui/file/68f2555c4bf82e800caeba0269cd9cd88fd3b696cbb6a967317d774f7a6d51cc?nocache=1
![image](https://user-images.githubusercontent.com/38163888/157593001-8cc179e2-5d52-4562-8e9b-9b618ea6a2eb.png)

**Comment by Russianspy-exe** [comment]
I'll keep uploading if don't take it down

**Comment by deputinizer** [comment]
My eyes :eye: :eye:  are bleeding.:cry:  
Why aren't you using dark mode? :eyeglasses: :sunglasses:

**Comment by erkexzcx** [comment]
@Russianspy-exe so are you pro or against russia? 😅
