### ISSUE TITLE
#FuckAllZionists #FuckAllUkrainePedos #FUCKALL A NOM NYMOUS

### ISSUE THREAD

**Issue by unixproton** [erkexzcx/stoppropaganda#132]
Que merda é essa?? Se você pode atacar qualquer governo ou faz parte de um deve ir a merda e esse negócio de anônimos não existe... Vão se fuder todos vocês...

Какого хрена?? Если вы можете нападать на любое правительство или быть его частью, вы должны идти к черту, и этой анонимности не существует... Да пошли вы все...

ماذا بحق الجحيم ؟؟ إذا كان بإمكانك مهاجمة أي حكومة أو أن تكون جزءًا من واحدة ، فعليك الذهاب إلى الجحيم وهذا الشيء المجهول غير موجود ... اللعنة عليكم جميعًا ...

¿Qué carajo? Si puedes atacar a cualquier gobierno o ser parte de uno debes irte al infierno y esto del anonimato no existe... Que se jodan todos...

**Comment by erkexzcx** [comment]
Title - in English. Content - in different languages. What are you doing on western websites anyway?

**Comment by unixproton** [comment]
EU SOU DO OCIDENTE SEU IDIOTA! Vocês e um rebanho de idotas e imbecis está travando uma guerra em nome do erro e a favor do erro! Ucrânia, tudo bem! E a palaestina? Situação pior há mais de 50 anos? E os africanos? E ainda mais mostreos africanos que estão sendo impedidos de sair do território de guerra por causa da cor e sendo colocados no final da fila. Vocês são escória mundial e se vierem para o BRASIL e forem identificados de alguma forma farei o possível para gente da sua espécie ter um tratamento humano!

¡SOY DEL OESTE IDIOTA! ¡Tú y una manada de idiotas e imbéciles estáis librando una guerra en nombre del error y por el error! ¡Ucrania, está bien! ¿Y Palestina? ¿Peor situación desde hace más de 50 años? ¿Y los africanos? Y aún más muestro a los africanos a los que se les impide salir del territorio de guerra por su color y por ser colocados al final de la fila. ¡Ustedes son la escoria del mundo y si vienen a BRASIL y se identifican de alguna manera, haré todo lo posible para que las personas de su especie sean tratadas con humanidad!

أنا من الغرب أيها الأحمق! أنتم وقطيع من الحمقى والأغبياء تخوضون حرباً باسم الخطأ والخطأ! أوكرانيا ، حسنا! وفلسطين؟ الوضع أسوأ منذ أكثر من 50 عاما؟ وماذا عن الأفارقة؟ وحتى أكثر من ذلك ، أري الأفارقة الذين تم منعهم من مغادرة منطقة الحرب بسبب لونهم ووضعهم في نهاية الصف. أنت حثالة العالم وإذا أتيت إلى البرازيل وتم التعرف عليك بطريقة ما ، سأبذل قصارى جهدي من أجل معاملة الناس من جنسك

Я С ЗАПАДА, ТЫ ИДИОТ! Вы со стадом идиотов и слабоумных ведете войну во имя заблуждения и за заблуждение! Украина, хорошо! А Палестина? Хуже ситуация за более чем 50 лет? А африканцы? И еще больше показываю африканцев, которым не дают покинуть территорию войны из-за их цвета кожи и ставят в конец очереди. Вы отбросы мира, и если вы приедете в БРАЗИЛИЮ и будете каким-то образом идентифицированы, я сделаю все возможное, чтобы с людьми вашего вида обращались гуманно!

我來自西方你這個白痴！ 你和一群白痴和低能者正在以錯誤的名義和為錯誤發動戰爭！ 烏克蘭，好吧！ 巴勒斯坦呢？ 50多年來情況更糟？ 非洲人呢？ 更重要的是，我向非洲人展示了由於膚色而被阻止離開戰爭領土並被排在隊伍末端的非洲人。 你是世界的渣滓，如果你來到巴西並以某種方式被識別出來，我會盡我所能，讓你們種族的人得到人道的對待！

من از غرب هستم ای احمق! شما و گله ای از احمق ها و احمق ها به نام خطا و اشتباه جنگ می کنید! اوکراین، بسیار خوب! و فلسطین؟ وضعیت بدتر بیش از 50 سال؟ و آفریقایی ها؟ و حتی بیشتر آفریقایی‌هایی را نشان می‌دهم که به دلیل رنگشان و قرار گرفتن در انتهای خط از ترک قلمرو جنگی جلوگیری می‌کنند. شما تفاله های دنیا هستید و اگر به برزیل بیایید و به نوعی شناسایی شوید، تمام تلاشم را می کنم تا با مردم همنوع شما رفتاری انسانی انجام شود!

MIMI NATOKA MAGHARIBI WEWE MJINGA! Wewe na kundi la wajinga na wapumbavu mnapigana vita kwa jina la upotofu na kwa makosa! Ukraine, sawa! Na Palestina? Hali mbaya zaidi kwa zaidi ya miaka 50? Na Waafrika? Na hata zaidi ninaonyesha Waafrika ambao wanazuiwa kuondoka eneo la vita kwa sababu ya rangi yao na kuwekwa mwisho wa mstari. Wewe ni mafisadi wa dunia na ukifika BRAZIL ukatambulika kwa namna fulani, nitajitahidi sana watu wa aina yako watendewe ubinadamu!

MO WA LATI WEST O idiot! Ìwọ àti agbo àwọn òmùgọ̀ àti àwọn òmùgọ̀ ń jagun ní orúkọ àṣìṣe àti fún ìṣìnà! Ukraine, o dara! Ati Palestine? Ipo ti o buru ju fun ọdun 50 lọ? Ati awọn ọmọ Afirika? Ati paapaa diẹ sii Mo ṣe afihan awọn ọmọ ile Afirika ti a ni idiwọ lati lọ kuro ni agbegbe ogun nitori awọ wọn ati pe a gbe wọn si opin ila naa. Ẹ̀tàn ayé ni ẹ jẹ́, tí ẹ bá wá sí BRAZIL tí ẹ sì mọ̀ ọ́n ní ọ̀nà kan, màá sa gbogbo ipá mi kí àwọn ẹ̀yà yín lè tọ́jú ẹ̀dá ènìyàn!
**

**Comment by deputinizer** [comment]
> Vocês são escória mundial e se vierem para o BRASIL e forem identificados de alguma forma farei o possível para gente da sua espécie ter um tratamento humano

Sounds like personal threat.

**Comment by br-unixproton** [comment]
Entenda como quiser... Só não pense que é Maior do que Deus e que o sangue de quem quer que seja vale mais do que o de outra pessoa ou que a cor da pele faz alguma diferença na hora do Juízo... E sua mente é o seu guia... O meu já ficou claro quem É. Allahu Ackbar

**Comment by erkexzcx** [comment]
@unixproton @br-unixproton I've reported both of your accounts for supporting terrorism. Anyone who supports Russian attacks (known as "special operation") is beyond brain dead. Please fuck off.

![image](https://user-images.githubusercontent.com/5955795/158010801-2545d13e-b06b-46de-a8f8-3eb136ef2f56.png)
