### ISSUE TITLE
-anticache=true is kinda slow

### ISSUE THREAD

**Issue by deputinizer** [erkexzcx/stoppropaganda#142]
Takes 20% of the CPU.

![image](https://user-images.githubusercontent.com/100740281/158125752-764f2348-4c4c-4010-8b8e-ddc954bac0ff.png)

Also with `-anticache=false` i'm getting rx: 500 Mbit/s
But with `-anticache=true` that's only rx: 30 Mbit/s (but outbound traffic spikes - tx: 300 Mbit/s)

**Comment by mjoyce91** [comment]
Higher traffic speed doesn't necessarily mean "better" though. The goal is to create requests that cause the server to think opposed to getting cached resources.

**Comment by deputinizer** [comment]
You're right. Too bad fasthttp isn't that fast and the 500 Mbit/s upload and download is not maxed out on a pretty good 2 vCPU.

**Comment by erkexzcx** [comment]
I've added below commits to improve the performance:

- https://github.com/erkexzcx/stoppropaganda/commit/9db1bab1cecd245f339bba1fe30c1c73296d0f1a
- https://github.com/erkexzcx/stoppropaganda/commit/3645f77cc87122aaa48835820f67de03c88385a9

**Comment by erkexzcx** [comment]
New version is up. Let me know how it performs on your machine now. :)

**Comment by deputinizer** [comment]
Nothing changed. Still 19% from fasthttp. Your RNG is still 0% (and was 0%).
![pprof 2022-03-15](https://user-images.githubusercontent.com/100740281/158318978-940618c1-05a1-49a0-bf1c-1bedbbeebb0b.png)

**Comment by deputinizer** [comment]
Fixed in https://github.com/erkexzcx/stoppropaganda/pull/145/commits/7b900a2278e81bf3dd06c59a28aa32d84162601f
