### ISSUE TITLE
Some facts...

### ISSUE THREAD

**Issue by lfdominguez** [erkexzcx/stoppropaganda#21]
Ohhh where you are when EEUU attack Irak??? Where you are when EEUU attack Afganistan??... and so on.... ahh Russia, because is Russia....
First learn about history... learn about how the member of SS (yes the secret service of Fascism on Hittler era) are legally members of army of Ukraine.... or where you are when the Ukraine army (yes, the neo-nazis) kills a lot of people on these country??? you dont known ANY OF THE HISTORY... so before go and do a Russian DDoS, learn something of history...
Ahhh, the thing is that any member of you family or your friends dont known anything about fascism... shame of you

**Comment by erkexzcx** [comment]
I really don't care of what Russians did or did not in the past.

At the moment they are invading Ukraine and killing its people, so **you can shut the fuck up**.

**Comment by micielski** [comment]
i'll be upgrading my bandwidth in 2 days from 500mbps to 1gbps
hope it will hit even harder with my dedicated machine and 2 different public ip mfers :3

**Comment by 3zero2** [comment]
@lfdominguez, go fuck yourself!

**Comment by erkexzcx** [comment]
@lfdominguez  _Русский военный корабль, иди нахуй!_

**Comment by lfdominguez** [comment]
Your responses are typical of only have 1 neuron... i understand you, ok if you thin that you and that other dumb people that think that you can get a DDoS to the internal network of Russia, BUAJAJAJAJAJAJA, you dont known anything about network systems and much less about internal Russia intranet, disconnected physical from the Internet... go and study network administration or telecommunications first....

**Comment by lfdominguez** [comment]
Ahh and if your ISP block you and the people that follow this kind of behavior, dont cry....
