### ISSUE TITLE
put site lists in the json file & grab it dynamically from github server every time the script is run

### ISSUE THREAD

**Issue by lamualfa** [erkexzcx/stoppropaganda#28]
put the site lists in a json file and then grab it via `raw.githubusercontent.com` server every time the script is run.

the pros of this method is we can update the site list every time and every where without forcing the old user to pulling the new version of this script from this repo.

**Comment by erkexzcx** [comment]
This would become a killswitch and I am not doing it. Related: https://github.com/erkexzcx/stoppropaganda/issues/10
