### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by RusskijKorablIdiNaxuj** [erkexzcx/stoppropaganda#30]
I've seen you have better luck promoting your tool:)
I've created one that is built with a GUI here: https://github.com/RusskijKorablIdiNaxuj/RusskijKorablIdiNaxuj
You have more targets. Perhaps it is possible to collaborate?

**Comment by erkexzcx** [comment]
Hi. Great project, but I will stick to CLI tool only :)

I also have plans to develoeper a proper HTLM-based web interface with tables, so it's easier than seeing JSON.

Regarding collaboration - I am not sure. Just stick to https://t.me/itarmyofukraine2022 instructions and you will have almost the same list!

**Comment by RusskijKorablIdiNaxuj** [comment]
My tool can also be built into a cli (I just don't include it in the release). There's a docker container too(I haven't pushed it to dockerhub yet).
Also, I'm working on building it into WASM so that it can be deployed on the web as the other tools so more people could use it...
What I meant by collaboration was including more attack vectors. I've added DNS, there is a need to attack smtp and pop3/imap, other services like databases, APIs, etc. 
My knowledge of these protocols is rather rusty...

**Comment by RusskijKorablIdiNaxuj** [comment]
Perhaps you can share tips on how to promote this kind of stuff? :)

**Comment by erkexzcx** [comment]
Share a link in a few places and if people likes your project - it will get popular automatically. Also post it on reddit `r/hacking`.
