### ISSUE TITLE
[suggestion] - what about DNS?

### ISSUE THREAD

**Issue by baylanger** [erkexzcx/stoppropaganda#36]
How about adding some "DNS" functionality to further help stop a propaganda? 🤔 

I'm not a Go programmer :/

**Comment by erkexzcx** [comment]
It's already added..?

**Comment by baylanger** [comment]
Yeah I see that now... not sure when it was added but I'm glad to see "DNSWorkers" option does it.

Closed!

**Comment by baylanger** [comment]
Yeah I see that now... not sure when it was added but I'm glad to see "DNSWorkers" option does it.

Closed!

**Comment by baylanger** [comment]
I'm actually reopening.  Who's DNS server are these belongs to, from source code :

```
194.54.14.186
194.54.14.187
194.67.7.1
194.67.2.109
```

Aren't we supposed to go after "ru" root servers / do we need to add more IPs to the list?

```
a.dns.ripn.net 193.232.128.6
b.dns.ripn.net 194.85.252.62
d.dns.ripn.net 194.190.124.17
e.dns.ripn.net 193.232.142.17
f.dns.ripn.net 193.232.156.17
```

**Comment by erkexzcx** [comment]
From IT army of Ukraine Telegram group: https://t.me/itarmyofukraine2022/61

--

At the moment, people in russia are withdrawing money from ATMs en masse. We can inflict enormous damage by hitting the DNS savings bank!
 
Our goal is www.sberbank.ru

194.54.14.186 : 53  UDP 
194.54.14.187 : 53  UDP 
194.67.7.1 : 53 UDP 
194.67.2.109 : 53 UDP

**Comment by baylanger** [comment]
Great idea to hit the bank..... fyi checking on sberbank.ru and I now see 6 servers listed.  Shall we update that list?

```
ns1.sberbank.ru 194.54.14.186
ns2.gldn.net    194.67.2.109
ns2.sberbank.ru 194.54.14.187
ns3.gldn.net    194.67.7.1
ns3.sberbank.ru 84.252.147.118
ns4.sberbank.ru 84.252.147.119
```
