### ISSUE TITLE
Code optimisations & improvements

### ISSUE THREAD

**Issue by erkexzcx** [erkexzcx/stoppropaganda#40]
This application greatly uses CPU and I am looking for a ways on how to optimise it further. Any MRs are welcome, preferably from Go developers!

Ideas for optimisation:
- **DONE** https://github.com/erkexzcx/stoppropaganda/blob/main/internal/stoppropaganda/websites.go#L248-L258 (reduce CPU usage in here?)
- **DONE** https://github.com/erkexzcx/stoppropaganda/blob/main/internal/stoppropaganda/websites.go#L262-L268 (reduce CPU usage in here?)
- https://github.com/erkexzcx/stoppropaganda/blob/main/internal/stoppropaganda/dns.go#L32-L54 (at least it works as expected, but is it possible to inflict more load on DNS server and/or use less CPU on host machine somehow? I have not worked with this lib and there seem to be no native Go functionality to specify custom DNS server. [This does not work](https://stackoverflow.com/a/59889883).)
- How about HTTPS websites and https://github.com/valyala/fasthttp client? Would it be doable?

Also can anyone guide me on how to setup Github actions for releasing with a click of a button?
- Github releases
- Dockerhub multiarch images

Golang binaries can be compiled for all architectures without using any virtualization (see build.sh) - can this be used to optimise building and publishing? Currently I am using `docker buildx build` and it builds in virtual environments with different architectures...

**Comment by Toxyl** [comment]
https://github.com/valyala/fasthttp/blob/master/client_test.go#L469 - this looks like fasthttp should be able to deal with HTTPS

**Comment by KeElena** [comment]
**https://github.com/torvalds/linux/tree/42194adcee11c339872fc874d0d0b9f77f84c932**
Indulge in Diana, then delete the library and run away

**Comment by bolsunovskyi** [comment]
Maybe it would be better to set default timeout to zero so we don't waste time on waiting for response and send more requests ?!

**Comment by Toxyl** [comment]
> Maybe it would be better to set default timeout to zero so we don't waste time on waiting for response and send more requests ?!

wouldn't that cause most requests to fail before they are even sent? at least when proxying through tor I noticed that a too low timeout would result in no requests arriving at the target.

**Comment by baylanger** [comment]
> Maybe it would be better to set default timeout to zero so we don't waste time on waiting for response and send more requests ?!

In udp world, afaik this should work just fine.

**Comment by baylanger** [comment]
I've created this PR for DNS timeout, fell free to comment.

https://github.com/erkexzcx/stoppropaganda/pull/43

**Comment by erkexzcx** [comment]
> https://github.com/valyala/fasthttp/blob/master/client_test.go#L469 - this looks like fasthttp should be able to deal with HTTPS

I will experiement with it. Resource-wises this should be significantly faster than using default `net` library.

**Comment by erkexzcx** [comment]
> https://github.com/valyala/fasthttp/blob/master/client_test.go#L469 - this looks like fasthttp should be able to deal with HTTPS

I've done it, but there seems to be no CPU improvements as well as CPU usage grows over time. I have no clue why. See https://github.com/erkexzcx/stoppropaganda/tree/dev2

**Comment by erkexzcx** [comment]
Looks like everything is implemented & fixed by now (at least what was originally mentiond in this issue). :)
