### ISSUE TITLE
Getting context deadline exceeded

### ISSUE THREAD

**Issue by kongolml** [erkexzcx/stoppropaganda#46]
I'm getting this kind of status only, can't figure out where is the issue using docker. Changing env variables doesn't help.
v.0.0.23

```
"http://belres.by/ru": {
    "requests": 3605,
    "errors": 3605,
    "last_error_msg": "Get \"http://belres.by/ru\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)",
    "status_100": 0,
    "status_200": 0,
    "status_300": 0,
    "status_400": 0,
    "status_500": 0
},
"http://belta.by": {
    "requests": 3600,
    "errors": 3600,
    "last_error_msg": "Get \"http://belta.by\": dial tcp 178.124.128.51:80: i/o timeout (Client.Timeout exceeded while awaiting headers)",
    "status_100": 0,
    "status_200": 0,
    "status_300": 0,
    "status_400": 0,
    "status_500": 0
}

**Comment by baylanger** [comment]
Have you tried to contact from your pc those web sites?

IF they are DOWN, timeout will show up. I just tested http://belta.by/ and it does seem down.

If all shows a timeout and from your pc you can reach the sites, then yes there might be an issue.  IF not please come back and close this issue.

**Comment by kongolml** [comment]
all shows one of those to errors. still i'm able to reach some of them from the browser, for example `https://ya.ru`
```
"https://ya.ru": {
  "requests": 15956,
  "errors": 15956,
  "last_error_msg": "Get \"https://ya.ru\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)",
  "status_100": 0,
  "status_200": 0,
  "status_300": 0,
  "status_400": 0,
  "status_500": 0
}

**Comment by baylanger** [comment]
At the top of the status page, are most of the DNS queries successful?  Trying to see if the instance can reach external network.

While checking on ^^^ I noticed at least mascom-it.ru now resolve to 127.0.0.1 @erkexzcx fyi 

Russian IT teams are trying to mitigate any downtime, etc

**Comment by kongolml** [comment]
```
"DNS": {
  "194.54.14.186:53": {
      "requests": 1447870,
      "success": 0,
      "errors": 1447870,
      "last_error_msg": "read udp 172.20.0.2:60698-\u003e194.54.14.186:53: i/o timeout"
  },
  "194.54.14.187:53": {
      "requests": 1448699,
      "success": 0,
      "errors": 1448699,
      "last_error_msg": "read udp 172.20.0.2:49666-\u003e194.54.14.187:53: i/o timeout"
  },
  "194.67.2.109:53": {
      "requests": 1447933,
      "success": 0,
      "errors": 1447933,
      "last_error_msg": "read udp 172.20.0.2:55262-\u003e194.67.2.109:53: i/o timeout"
  },
  "194.67.7.1:53": {
      "requests": 1446096,
      "success": 0,
      "errors": 1446096,
      "last_error_msg": "read udp 172.20.0.2:48374-\u003e194.67.7.1:53: i/o timeout"
  }
}

**Comment by baylanger** [comment]
If you go inside your Docker instance, can you ping any external network and can you resolve any hostname?

```docker exec -it <instance_name> /bin/bash (/bin/sh if /bin/bash isn't available)
ping 1.1.1.1
nslookup www.google.com (if nslookup not there, host should work)
```

On what type of brand/device (nas?) are you running your Docker instance?  Do you have other Docker instances running fine accessing the Internet?  If not there might be something missing in your config.

**Comment by micielski** [comment]
I have the same situation, I'm running just a linux binary (i'm running it on both debian and arch linux on an old laptop and computer respectively, both with different public IPs but with the same modem)
I have access to ISP's dashboard on how much internet I consume. first day (that was 2 days ago) I've been hitting it with 200GB (yes, gigabytes) per hour. Now i'm barely hitting 4GB.
I'm constantly trying to change different options and testing it, but nothing seems to work yet

**Comment by erkexzcx** [comment]
Hey ye'all. I am also getting `dial tcp 178.124.128.51:80: i/o timeout (Client.Timeout exceeded while awaiting headers)",` kind of errors and I believe they are expected. Those servers cannot handle such amount of traffic.

> While checking on ^^^ I noticed mascom-it.ru & elkursk.ru now resolve to 127.0.0.1 @erkexzcx fyi
Nice find! I will try to find a way to fix it (exclude private IPs from DOS), but unfortunately tomorrow...

**Comment by erkexzcx** [comment]
> While checking on ^^^ I noticed mascom-it.ru & elkursk.ru now resolve to 127.0.0.1 @erkexzcx fyi

**This is actually very dangerous**. They could change their domains to something that points to Facebook, Google, Microsoft etc and basically we unintentionally DDOS non-russian websites. Not good!

**Comment by kongolml** [comment]
> 

using mac os.
command gives me `OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown` (same for /bin/bash)

**Comment by kongolml** [comment]
> If you go inside your Docker instance, can you ping any external network and can you resolve any hostname?
> 
> ```
> docker exec -it <instance_name> /bin/bash (/bin/sh if /bin/bash isn't available)
> ping 1.1.1.1
> nslookup www.google.com (if nslookup not there, host should work)
> ```
> 
> On what type of brand/device (nas?) are you running your Docker instance? Do you have other Docker instances running fine accessing the Internet? If not there might be something missing in your config.

using mac os.
command gives me OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown (same for /bin/bash)

**Comment by erkexzcx** [comment]
> While checking on ^^^ I noticed mascom-it.ru & elkursk.ru now resolve to 127.0.0.1 @erkexzcx fyi

https://github.com/erkexzcx/stoppropaganda/pull/48 fixes this. Let me quickly release a new version.

**Comment by erkexzcx** [comment]
New version is out

**Comment by erkexzcx** [comment]
Tomorrow I will check if it's possible to pre-resolve domain to IP addresses and cache it locally for some time. This would reduce amount of timeout errors and reduce load on DNS servers used by application's host.

**Comment by kongolml** [comment]
on mac os issue is still persist
container cli gives me OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown (same for /bin/bash)

**Comment by erkexzcx** [comment]
Guys, open a new issue if you are still facing this with latest release.

Note the meaning of `last_error_msg` - **getting timeouts is a good thing** and that's exactly what you are trying to achieve.
