### ISSUE TITLE
ASN# lookup - prevent DOS outside of destination countries

### ISSUE THREAD

**Issue by baylanger** [erkexzcx/stoppropaganda#49]
This [commit](https://github.com/erkexzcx/stoppropaganda/pull/48/commits/62f7ce02d19069a560ba740d1fbf67378541a326) added "local IP" lookup to prevent self DOS.

There are lists available that list all ip-netblocks / country.  To prevent DOS outside of the countru, possibly Ukraine or?  I suggest we import the list.  Perhaps a go module already exists?

I'd work on this but I don't have time now, if *you* want to take ownership of this issue just reply and go ahead :)

**Comment by erkexzcx** [comment]
I ws actually planning to implement this tomorrow. :)

**Comment by baylanger** [comment]
For sites using https : if the IP points to, for example a Google IP in the US or Russia, the SSL handshake would fail.  When this happen can we print stderr a log and exit/stop the workers.

For https , is the ASN# lookup needed?  I don't think so but a log is required so we can adjust if ever needed.

If the site returns a redirect, we probably don't want to follow it - but if the destination ends with .ru or .by , should we at least log the redirect.  I am thinking some sites are probably adding quick redirects as a solution that is "cost effective".

Side note, if we don't have that info, we should look into adding rest-api that smart app use to do bank transactions, not only the "main" bank web site.  Their Stock Exchange is expected to open on Monday 🤔

**Comment by erkexzcx** [comment]
> if the IP points to, for example a Google IP in the US or Russia, the SSL handshake would fail.

I disabled TLS verification on purpose. Do you think this is a good thing to enable it? I would prefer validating whether the destination IP that is being resolved by DNS is actually in Russia and/or Belarus. If not - pause workers and re-check in 5 mins.

> If the site returns a redirect, we probably don't want to follow it

Correct. DOS'int front facing load balancer/gateway is as good as server itself - it causes downtime.

> we should look into adding rest-api that smart app use to do bank transactions

Correct, but I really don't have time to focus on scanning for such domains/ips and contributions are welcome!

**Comment by baylanger** [comment]
> I disabled TLS verification on purpose. Do you think this is a good thing to enable it? I would prefer validating whether the destination IP that is being resolved by DNS is actually in Russia and/or Belarus. If not - pause workers and re-check in 5 mins.
> 
My guess is that if a client certificate is required, the site will continuously return errors.  When using https maybe we should do a 1 test with TLS to see if the handshake fails, if so don't move forward?   I'm talking loud here.. not sure best approach yet.

> > If the site returns a redirect, we probably don't want to follow it
> 
> Correct. DOS'int front facing load balancer/gateway is as good as server itself - it causes downtime.
> 
I don't know what the go client allows, can we use persistent connection or are we already using it?  This keeps the port open non stop and should stress more their server (cpu) and possibly run out of TCP ports.  Maybe after X queries (100?) we close and re-open just in case DNS address changed, etc?!?!  Again talking loud :)

> > we should look into adding rest-api that smart app use to do bank transactions
> 
> Correct, but I really don't have time to focus on scanning for such domains/ips and contributions are welcome!
>
In my "add api sites" PR, I know Stock exchange API if in there and Monday I plan to focus on this one.

Should we add a note in the README to mention the stock exchange Monday opening?

Wish we could have a scheduler that uses ifttt or ?! to coordinate systems together.

**Comment by erkexzcx** [comment]
I don't think this issue is going anywhere. There are multiple international domains in-use and we want to DOS russian companies outside russia as well.
