### ISSUE TITLE
dynamic proxy problem.

### ISSUE THREAD

**Issue by safciplak** [erkexzcx/stoppropaganda#57]
we've to use the dynamic proxies. 
we can populate the proxies.
like sort of these type of websites.

https://free-proxy-list.net/ 
https://hidemy.name/en/proxy-list/

**Comment by erkexzcx** [comment]
Can you try to explain your problem?

**Comment by baylanger** [comment]
@safciplak do you have an example?  Are you saying we could use one of the Russian proxy site to attack a site that is protected via a proxy?  If so again please give a concrete example.

And you refer to the list in here? https://github.com/erkexzcx/stoppropaganda/pull/58

**Comment by erkexzcx** [comment]
Lacks documentation, but support added to v0.0.30. See https://github.com/erkexzcx/stoppropaganda/pull/76
