### ISSUE TITLE
[discuss] Iran provides arms to Russia

### ISSUE THREAD

**Issue by baylanger** [erkexzcx/stoppropaganda#65]
[EDIT] The discussion is now specific to Iran's entities fabricating arms sold to Russia that kill Ukrainians.

Starting a discussion.

Is it time to add countries/non Russian entities that supports Putin?  The countries below support Putin, some are supplying arms to Russia and some are just silent.

- Iran is one country that can back Russia as it supplied arms to the country.

Something should be done here and ASAP.  Should we at least target manufacturers and military, or more?  Comments?

- Cuba, a close ally of Russia, has sharply criticized the US for imposing the progressive expansion of NATO towards the Russian borders and called for a diplomatic solution to preserve international peace.

We could easily bring down Cuba Internet pipe... for the URL is it better to use something like : https://www.cuba.xxxx/Fuck_Russia  - the logs will show "Fuck_Russia" so IT teams can tell their government what's happening.

- Pakistan gets a special mention as its Prime Minister Imran Khan could think of no other time to visit Moscow but now when Russia is in the middle of a war against Ukraine.

- Armenia, Kazakhstan, Kyrgyzstan, Tajikistan and Belarus are expected to support Russia due to the Collective Security Treaty Organisation (CSTO) agreement signed between the six countries.  This means that in case of an attack on Russia, these countries will consider it an attack on themselves.

- India

**Comment by erkexzcx** [comment]
Some countries do support Russia aggression, but they do not have their military in Ukraine that kills innocent people. :shrug: Also I don't want to be the one who decices who are good and who are bad.

What is clear now that Belarus and Russia are cooperating and both should be responsible for what is happening in Ukraine.

**Comment by baylanger** [comment]
Good point.

Iran's missiles, etc are killing Ukrainians - is it fine to target the entities being those arms?

People can Up or Down vote.

If the list gets split into multiple "type of entities" , we could have a flag like "-dos_iran_arms" ?!   Thinking about this... if we split, we might want to have a "default" variable that defines if the list by default is active or not and the end user could adjust.  Perhaps we even want to have weight value => increased or reduce the number of workers.

**Comment by erkexzcx** [comment]
I don't know. Let's just stick to IT Army of Ukraine and their given targets. They know better than us of what needs to be taken down.

**Comment by baylanger** [comment]
I was going over this again in my mind, maybe we don't want to frustrate Iran too much for now in case they decide to send their army!
