### ISSUE TITLE
fasthttp: crash SIGSEGV bytebufferpool.Reset

### ISSUE THREAD

**Issue by deputinizer** [erkexzcx/stoppropaganda#72]
`./dist/stoppropaganda_v0.0.26_linux_x86_64 -workers 1 -dnsworkers 1 2> err.txt`

Commit https://github.com/erkexzcx/stoppropaganda/commit/965d2c7945b9bf109d35d3be5d2ef3cf62036d89

Machine has 2 vcpus / 2 threads

```
$ head -n 100 err.txt
2022/03/02 16:35:06 Started!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x68252b]

goroutine 5377639 [running]:
github.com/valyala/bytebufferpool.(*ByteBuffer).Reset(...)
        /home/test/stoppropaganda/vendor/github.com/valyala/bytebufferpool/bytebuffer.go:110
github.com/valyala/fasthttp.(*Response).ReadBody(0xc00005fb00, 0xc00148efc0, 0x572546)
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/http.go:1295 +0xab
github.com/valyala/fasthttp.(*Response).ReadLimitBody(0xc00005fb00, 0x77fb30, 0xc000ced500)
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/http.go:1274 +0xd8
github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp(0xc000cf7ba0, 0xc0006b7500, 0xc00005fb00)
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:1455 +0x50c
github.com/valyala/fasthttp.(*HostClient).do(0xc000640e88, 0x680765, 0xc00005fb00)
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:1347 +0x79
github.com/valyala/fasthttp.(*HostClient).Do(0xc000cf7ba0, 0xc0006b7500, 0xc00122dc40)
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:1294 +0x91
github.com/valyala/fasthttp.(*Client).Do(0xc00008e200, 0xc0006b7500, 0xc000640f01)
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:528 +0x585
github.com/valyala/fasthttp.clientDoDeadline.func1()
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:1220 +0x79
created by github.com/valyala/fasthttp.clientDoDeadline
        /home/test/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:1218 +0x418

$ go version
go version go1.17.7 linux/amd64
```

**Comment by 0xzheo** [comment]
I also have this error on raspberry pi

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x2823c4]

goroutine 3037694 [running]:
github.com/valyala/bytebufferpool.(*ByteBuffer).Reset(...)
	/home/pi/stoppropaganda/vendor/github.com/valyala/bytebufferpool/bytebuffer.go:110
github.com/valyala/fasthttp.(*Response).ReadBody(0x2197860, 0x20df320, 0x0)
	/home/pi/stoppropaganda/vendor/github.com/valyala/fasthttp/http.go:1295 +0x98
github.com/valyala/fasthttp.(*Response).ReadLimitBody(0x2197860, 0x20df320, 0x0)
	/home/pi/stoppropaganda/vendor/github.com/valyala/fasthttp/http.go:1274 +0xec
github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp(0x201ed20, 0x25184e0, 0x2197860)
	/home/pi/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:1455 +0x69c
github.com/valyala/fasthttp.(*HostClient).do(0x201ed20, 0x25184e0, 0x2197860)
	/home/pi/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:1347 +0x80
github.com/valyala/fasthttp.(*HostClient).Do(0x201ed20, 0x25184e0, 0x2197860)
	/home/pi/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:1294 +0x88
github.com/valyala/fasthttp.(*Client).Do(0x1d101e0, 0x25184e0, 0x2197860)
	/home/pi/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:528 +0x544
github.com/valyala/fasthttp.clientDoDeadline.func1(0x2540bdabe, 0x25184e0, {0x359d84, 0x1d101e0}, 0x2197860, 0x2b58e30, 0x2b58e38, 0x1e05c70, 0x1d82b60, 0x2c26cc0, ...)
	/home/pi/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:1220 +0x44
created by github.com/valyala/fasthttp.clientDoDeadline
	/home/pi/stoppropaganda/vendor/github.com/valyala/fasthttp/client.go:1218 +0x354
```

**Comment by deputinizer** [comment]
So race condition is here:
https://github.com/valyala/bytebufferpool/blob/master/bytebuffer.go#L110

We can't release response multiple times:
https://github.com/erkexzcx/stoppropaganda/blob/main/internal/stoppropaganda/websites.go#L412
after they are created once:
https://github.com/erkexzcx/stoppropaganda/blob/main/internal/stoppropaganda/websites.go#L330

**Comment by deputinizer** [comment]
So let's do:
```golang
fasthttp.AcquireResponse()
```
For every request just like:
https://github.com/valyala/fasthttp/blob/master/examples/client/client.go#L75

**Comment by erkexzcx** [comment]
Hmmm. Let me take a look.

**Comment by erkexzcx** [comment]
> We can't release response multiple times
> ...
> after they are created once

Do you have a link to documentation regarding this? I've spent quite some time today digging into fasthttp documentation. :thinking:

**Comment by deputinizer** [comment]
> Do you have a link to documentation regarding this? I've spent quite some time today digging into fasthttp documentation. thinking

Well it's obvious we can't reset many times a once released buffer.
https://github.com/valyala/fasthttp/blob/master/http.go#L1295

**Comment by erkexzcx** [comment]
Probably you are right. I will release new version shortly. Thanks!

**Comment by erkexzcx** [comment]
Wait, what if we don't call `fasthttp.ReleaseResponse(...)`?

**Comment by deputinizer** [comment]
Hmmm fasthttp uses goroutines by itself so...
```golang
// Response instance MUST NOT be used from concurrently running goroutines.
```
https://github.com/valyala/fasthttp/blob/v1.33.0/http.go#L69

**Comment by erkexzcx** [comment]
Can you try if you are getting the error now? https://github.com/erkexzcx/stoppropaganda/blob/main/internal/stoppropaganda/websites.go

Acquiring on every cycle uses resources, so I would like to avoid unnecesarry cpu usage.

**Comment by deputinizer** [comment]
On my commit https://github.com/deputinizer/stoppropaganda/commit/bdd16864d126f2e5e495835c6c77b2eac0710428
it didn't crash so far.
```
time ./stoppropaganda -workers 1 -dnsworkers 1 2> err.txt
^C

real    16m30.159s
```

**Comment by deputinizer** [comment]
> Can you confirm that my code don't actually stream from pre-downloaded response body?

It actually copies the pre-downloaded content 😅
https://github.com/valyala/fasthttp/blob/v1.33.0/http.go#L498

Because `bodyBytes()` is an internal buffer :smiley: 
https://github.com/valyala/fasthttp/blob/61aa8b17a240b66ead927f945a3e8a96c3f0ec40/http.go#L342

**Comment by erkexzcx** [comment]
Anyway, let's release now an updated version and see if we can improve it in the next releases

**Comment by erkexzcx** [comment]
So, thank you so much for your contribution. :100:  If you have any ideas on how to optimise the code, please let me know or create pull request!

New version is out!

Слава Україні!
