### ISSUE TITLE
[Announcement] Now usable on Android

### ISSUE THREAD

**Issue by erkexzcx** [erkexzcx/stoppropaganda#78]
See https://github.com/erkexzcx/stoppropaganda#android

<img src="https://user-images.githubusercontent.com/5955795/156454591-46b33b8f-bed4-4d76-a872-a494c0cf4312.png" width="250">

**Comment by erkexzcx** [comment]
Looks like DNS is not resolving website domains but dns DOS works fine...

**Comment by Copro** [comment]
Would not start anything in termux ... small typo in the parameter dsntimeout which accepts milliseconds.
-dnstimeout (in milliseconds)

**Comment by baylanger** [comment]
@Copro where are you seeing this typo?  We'll get it fixed.
