### ISSUE TITLE
В деяких випадках задача зупиняється

### ISSUE THREAD

**Issue by DjSapsan** [erkexzcx/stoppropaganda#79]
Я запустив з нуля 5 ВМ. На одній з них була така проблема і через деякий час пропала (після кількох ребутів і запусків команд заново). Але на останній ВМ задача завжди зупиняється через 40-60 сек. Ніякої різниці між машинами не бачу. Якщо це краш, як узнати причину?

![image](https://user-images.githubusercontent.com/12209464/156461809-a4a58dc0-685d-49db-a8ad-21233b35e535.png)

**Comment by baylanger** [comment]
Do you have enough RAM?  ====>>> ??? У вас достатньо оперативної пам'яті?  ???

Try this config (Спробуйте цю конфігурацію ??) , docker-compose.yaml :

SP_WORKERS: "1"
SP_DNSWORKERS: "1"

Is it still crashing with this config?  Make sure to use latest Docker image, there were a few bugs in past ~24 hours ===> Він все ще аварійно завершує роботу з цією конфігурацією? Переконайтеся, що ви використовуєте останнє зображення Docker, за останні ~ 24 години було кілька помилок.

**Comment by baylanger** [comment]
https://www.translate.com/ukrainian-english 😄

**Comment by DjSapsan** [comment]
Дякую, добавив RAM, так зразу запрацювало :)
Thank you

**Comment by baylanger** [comment]
Скільки оперативної пам'яті?  Можливо, нам потрібно додати цю інформацію в РІДМЕ. @erkexzcx fy.

**Comment by DjSapsan** [comment]
@baylanger, було 1 ГБ, зробив 4

**Comment by DjSapsan** [comment]
@baylanger, схоже я туплю Де саме змінювати SP_WORKERS і т.п.? Я прописував в env через export. І чи це обов'язково по дефолту?

**Comment by baylanger** [comment]
@DjSapsan

docker-compose.yaml 

або

[Docker](https://github.com/erkexzcx/stoppropaganda/blob/6da510973eaa1f3a07e49a49d644f2f31a570b78/README.md#docker)

або

stoppropaganda --workers 10000 --dnsworkers 50000
