### ISSUE TITLE
Process killed (raspberry pi 4)

### ISSUE THREAD

**Issue by 0xzheo** [erkexzcx/stoppropaganda#84]
A minute after running the go program, it is getting killed. 'top' shows that the process's memory usage steadily increases from 1% to ~7% until it's killed, perhaps there is a memory leak?

```
pi@raspberrypi:~/stoppropaganda $ go build -o stop_propaganda cmd/stoppropaganda/main.go
pi@raspberrypi:~/stoppropaganda $ time ./stop_propaganda 
2022/03/03 XX:XX:XX Started!
Killed
```

**Comment by erkexzcx** [comment]
https://github.com/erkexzcx/stoppropaganda/releases

If you are using 32bit OS, download for `linux_armhf`. If you are using 64bit OS, download for `linux_aarch64`.

Personally [I would build on my desktop/laptop](https://github.com/erkexzcx/stoppropaganda/blob/main/build.sh) and upload binary to RPI via SSH, but your use case might be different - what do I know. :)

**Comment by erkexzcx** [comment]
It could also mean this app used all your RAM and was killed by OOM killer. Reduce amount of workers/dnsworkers and try again.
