### ISSUE TITLE
 Dynamic SP_USERAGENT

### ISSUE THREAD

**Issue by adrihanu** [erkexzcx/stoppropaganda#86]
What do you think about changing the `SP_USERAGENT` every `X` seconds? Some of the systems might be using `User-Agent` header to block/filter some requests, right? Could that improve efficiency?

In the past, I have used [Python module](https://pypi.org/project/user-agent). There is also [JavaScript package](https://github.com/intoli/user-agents) and [Go generator](https://github.com/corpix/uarand) based on it. What do you think?

**Comment by erkexzcx** [comment]
> Some of the systems might be using User-Agent header to block/filter some requests

I've set user agent to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36` which represents currently latest Google Chrome (and derivatives) on Windows PCs. Do you really think it would be wise for them to block this user agent? :)

Also I've considered dynamically changing user agent, but it would make it more easily blockable by blocking unknown user agents. :)

**Comment by adrihanu** [comment]
> [...] you really think it would be wise for them to block this user agent? 

For sure, they are not going to just block this `user-agent` completely. I was rather thinking that some AI systems for protection might see an unusually big increase in this `user-agent` and be more efficient in blocking such requests. It's quite difficult to predict how such a system might behave. It depends on what data they have been trained and tested on.

> [...] it would make it more easily blockable by blocking unknown user agents 

Yes, I agree, but the `JS` library I proposed is used to create realistic traffic patterns by generating a random user agent and other browser properties based on data which is updated automatically on a daily basis. As I said, I don't know how it would influence efficiency, maybe it's not worth trying.

**Comment by erkexzcx** [comment]
@deputinizer what do you think about https://github.com/corpix/uarand ? Would it be worth implementing?

**Comment by deputinizer** [comment]
Worth it :)
But https://github.com/corpix/uarand does not provide weights - Chrome 98 should be the most popular.

**Comment by erkexzcx** [comment]
https://github.com/erkexzcx/stoppropaganda/pull/135 been implementing which basically does what this issue described - cache busting. Randomising user agent will not bring any benefits over it and just uses more CPU & RAM.
