### ISSUE TITLE
Remeber Belgrad, Donetsk, Libya, Iraq

### ISSUE THREAD

**Issue by andrewisakov** [erkexzcx/stoppropaganda#9]
This war begin in 2013, and sponsored by Vashington. Russia end this war.

**Comment by taeraeyttaejae** [comment]
> 

You should probably go fuck yourself, putinist.

**Comment by erkexzcx** [comment]
@andrewisakov please visit this place sometime :) https://www.google.com/maps/place/+08270,+Peru/@-14.4098208,-71.3077453,15z

**Comment by andrewisakov** [comment]
А по-существу ?
