### ISSUE TITLE
Need new tactic - HTTP stats 200, 300, 400, 500

### ISSUE THREAD

**Issue by baylanger** [erkexzcx/stoppropaganda#90]
With the current ~285+ web sites , here are HTTP code stats from America.

```
code  # of websites
200   13
300   21
400   23
```

Private IPs = 5
Timeout = 223
Unknown host = 7

~ 223+5+23+21+13+7 = ~292

What can be done about this?

**Comment by baylanger** [comment]
Do we need cloud computing instances on Russian land

**Comment by baylanger** [comment]
When a web site timeout, can we pause for that site for a minute or perhaps even 5?

Reasons for a timeout : 

1) the site is down because of firewall tables, node is down, etc - nothing we can do, we waste resources. 
2) the site appears down because of ongoing DOS, if we pause this site the logic will focus on the ones that are still up.

There are so many timing out, it's a waste of resource from the pool.

**Comment by baylanger** [comment]
Also noticed the Moscow stock exchange had some imagination 🤣 

```
www.moex.com A 0.0.0.0
```

**Comment by deputinizer** [comment]
> www.moex.com A 0.0.0.0

Your ISP blocked this address with DNS

**Comment by baylanger** [comment]
@deputinizer are you postitive?

```
% dig a www.moex.com @1.1.1.1|grep ANSWER\  -A2
;; ANSWER SECTION:
www.moex.com.		566	IN	CNAME	cl-ae0978b2.gcdn.co.
cl-ae0978b2.gcdn.co.	26	IN	A	0.0.0.0
```

**Comment by baylanger** [comment]
Currently ru DNS servers aren't returning A/AAAA records for www..moex.com but some DNS like cloudflare returns 0.0.0.0.

Got to wonder if some entities are now returning different answers based on location. 🤔

**Comment by erkexzcx** [comment]
With next release I will exclude domains that resolve to 0.0.0.0

**Comment by erkexzcx** [comment]
> When a web site timeout, can we pause for that site for a minute or perhaps even 5?

Site could be down, but we want to keep it down, not "take a breath and get down again". No?

**Comment by baylanger** [comment]
Trying to avoid the pool to be utilized by too many threads hang and waiting for a timeout and thus possibly making things slower.

Exhausting all resources is definitely the goal - as long as a server if up and returning 200 it means there are still TCP ports available.  As soon as the ports are exhausted (tcp/web or udp/dns) and the tcp queues are full, the service is pretty much "dead".

When you suggested to add a flag not to wait for the data to be returned by the server, that should efficient.  The process downloads less data and the end point should be even more impacted because of higher rate/ sec of ports being assigned.

**Comment by baylanger** [comment]
Different issue, lazy to open another issue.

When running the application with `-dnstimeout 1ms` , most DNS queries should timeout but it doesn't seem to happen at all.  There's no difference between 1ms or 125ms.

**Comment by Toxyl** [comment]
> > When a web site timeout, can we pause for that site for a minute or perhaps even 5?
> 
> Site could be down, but we want to keep it down, not "take a breath and get down again". No?

exactly. but maybe an idea to mark when a site goes down, pause it for a few minutes and then throw it back into the mix?

**Comment by erkexzcx** [comment]
> When running the application with -dnstimeout 1ms , most DNS queries should timeout but it doesn't seem to happen at all. There's no difference between 1ms or 125ms.

For me there is a difference. :thinking: Are you using the latest version?

**Comment by baylanger** [comment]
dnstimeout does work now.  Closing this.  If we really need new strategy, we open new issue.
