### ISSUE TITLE
dial tcp4 xx.xx.xx.xx:443: connect: can't assign requested address

### ISSUE THREAD

**Issue by baylanger** [erkexzcx/stoppropaganda#91]
I've started to see this error showing up on all sites since past ~24 hours.

The process after ~2 minutes lags and pretty much stops to generate any traffic.  This is in a virtual MacOS instance ... regardless a vm or not, I'm not sure of the exact cause.  Perhaps some network settings need to be increased to allow more ports, bigger network queue etc.

If someone has an idea, please post.

**Comment by deputinizer** [comment]
How many open files are there? 65535 ? I this case, all TCP ports are just exhausted.

**Comment by baylanger** [comment]
Shell limit is 128k.

There's no "too many open files" showing up in the logs unless I lower the limit too low (< 10k).  Almost if I launch with, for example, 

```
-workers 4000  -timeout 2s --dnsworkers 1000 -dnstimeout 125ms
```

lsof -p shows the process is reaching ~20-30k fd.

```
% netstat -an |grep -v FIN_|wc -l
   21373
% netstat -an |grep -v CLOSED|wc -l
   17068
```

Will try to tune TCP driver and come back with a solution, I might not be the only one having this issue and unless someone digs around it's impossible to know the process is kind of jammed.

**Comment by baylanger** [comment]
@erkexzcx I'm still trying to understand .... my process lags and doesn't do much after a few minutes even after I made a few kernel changes.  I don't know where to look but are the Go http/dns libraries setting socket options with SO_REUSEADDR & SO_REUSEPORT ?

**Comment by deputinizer** [comment]
Ok i've made a change to spam TCP SYN less in https://github.com/erkexzcx/stoppropaganda/pull/93

**Comment by baylanger** [comment]
The latest changes in .34 fixes this issue.  Thank you @deputinizer @erkexzcx !
