### ISSUE TITLE
Упав трафік

### ISSUE THREAD

**Issue by DjSapsan** [erkexzcx/stoppropaganda#92]
Сьогодні після одного ребуту упав трафік, ніяк не можу підняти. Скрізь працюють докери з останнім релізом. Ребути і зміна параметрів не помогає.
![image](https://user-images.githubusercontent.com/12209464/156649400-ff6bdd6a-7663-4fac-8e72-d985623d9928.png)
Як виправити?

**Comment by baylanger** [comment]
Будь ласка, вставте конфігурацію, це може допомогти знайти першопричину.

Ви бачите помилки? => http://127.0.0.1:8049/status

**Comment by deputinizer** [comment]
Probably because of sleep/mutex in workers that effectively disables them. 
I'm working to remove sleep+mutex in order to dispatch workers for real work.

**Comment by baylanger** [comment]
@DjSapsan #93 вирішити проблему.

Зачекайте, поки наступна версія буде доступна найближчим часом.

**Comment by DjSapsan** [comment]
@baylanger status: https://pastebin.com/raw/XC4tMWmf

чекаю мердж з фіксом, а то 6 ВМ працюють на 5%

**Comment by GloryOfUkraine** [comment]
I have the same problem. Traffic is goes well just for some period of time after docker instance start. In few minutes it is fall down to 500kbps. The same issue exists in all my VPS instances around the world

**Comment by erkexzcx** [comment]
Should be fixed in v0.0.34. Please confirm whether the latest version fixes the issue.

**Comment by baylanger** [comment]
Not seeing this issue anymore (0.0.34).

**Comment by ALF-1991** [comment]
Досі проблеми у мене і у знайомих

**Comment by DjSapsan** [comment]
В Digital Ocean ледве піднявся до 500 Кб/с. Але до попередніх 15 Мб/с дуже далеко. В Azure майже не видно різниці, десь +5 %

**Comment by DjSapsan** [comment]
![image](https://user-images.githubusercontent.com/12209464/156786379-f8dbf0d7-c585-46d7-a0ae-3ca8630528cd.png)

**Comment by baylanger** [comment]
@ALF-1991 Будь ласка, розкажіть про те, що у вас є.  Ви бачите проблему в "/status" або щось інше?

**Comment by ALF-1991** [comment]
я зніс всі машини з переляку, роблю нові на ажурі, зараз закину інфу із Digital Ocean

**Comment by Okhrimenko** [comment]
I have same traffic problems. status error:

 "https://zakupki.gov.ru": {
            "requests": 187,
            "errors": 187,
            "last_error_msg": "httpClient.Do: CustomTCPDialer: 95.167.245.92:443 timed out",
            "status": "Running",
            "status_100": 0,
            "status_200": 0,
            "status_300": 0,
            "status_400": 0,
            "status_500": 0
        },

**Comment by ALF-1991** [comment]
http://143.244.210.66:8049/status

**Comment by baylanger** [comment]
0.0.34 - no issue below - немає проблем нижче

<img width="298" alt="2022-03-04_10-00-35" src="https://user-images.githubusercontent.com/5240348/156786800-57b1e057-2b6f-4078-b719-a3ac16b8980a.png">
 
@DjSapsan @ALF-1991 Ви впевнені, що у вас є версія .34?  Ви використовуєте Docker? Чи достатньо оперативної пам'яті?  Будь ласка, опублікуйте конфігурацію.

@erkexzcx should we add output of the application version (0.0.xx) at the top of the json output from /status?

@Okhrimenko the timeout is normal, it is because the site is currently down or unreachable.  Right?

**Comment by ALF-1991** [comment]
![image](https://user-images.githubusercontent.com/100792830/156788124-4cc50046-d67e-4106-9ee2-35302e3912c2.png)
![image](https://user-images.githubusercontent.com/100792830/156788210-ef612823-1e89-4afc-967d-6a00d9096bd0.png)
[статус.txt](https://github.com/erkexzcx/stoppropaganda/files/8186799/default.txt)

**Comment by baylanger** [comment]
намагатися 4GB ?

Статистика подібна до моєї.  Багато www мають захист або вниз.  Це нормально, щоб побачити тайм-аут і домену не існує.

**Comment by ALF-1991** [comment]
Зараз створюю на Ажурі  Standard D2s v3 (2 vcpus, 8 GiB memory), відпишу результат

**Comment by ALF-1991** [comment]
Те саме

**Comment by DjSapsan** [comment]
більші значення в docker run --name stoppropaganda **-e SP_WORKERS=100000 -e SP_DNSWORKERS=500000** -td --ulimit nofile=128000:128000 -p "8049:8049/tcp" erikmnkl/stoppropaganda
зробили мізерну добавку. Версія latest
![image](https://user-images.githubusercontent.com/12209464/156799413-1a7e224b-6353-470a-9118-92a9c6926cfb.png)

**Comment by DjSapsan** [comment]
не помогло, все через 5 хв упало. 
@baylanger , перевірте мій форк https://github.com/DjSapsan/stoppropaganda
