### ISSUE TITLE
Bring back per-website workers: TCP connections limit [fail2ban]

### ISSUE THREAD

**Issue by deputinizer** [erkexzcx/stoppropaganda#96]
Some websites, eg. `tass.ru` block all TCP connections from a given IP probably if:
- we make 2+ connections at the same time from one IPv4
- we spam HTTP GET in a weird way?

Therefore, we should limit how many fasthttp connections there are at any moment.
1 worker [goroutine per website] in v0.0.29 did actually fix the problem.

**Comment by baylanger** [comment]
New generation firewalls have built with AI systems in place reading "time series" data often using influxdb as the backend.  The data consist of network/system/app logs & events.

Russia likely doesn't have access to those products but it only takes a good programmer write few code to read http access log file - but not all entities have people on site with good knowledge to tackle this problem.  There are probably forums in .ru/.by countries where "IT people" exchange ideas to put counter measures and how to get things under control.

 "ruby" (.ru .by) is a beautiful stone but written the opposite way, bury.  Bury the ruby soldiers.

<img width="509" alt="2022-03-03_23-01-03" src="https://user-images.githubusercontent.com/5240348/156697015-b56dcae1-ac64-48a6-ac88-9f2ffcb54533.png">

If we'd google around we could find what options are available but those exists : 

max conn / sec allowed
syn attack
IP country origin
...

For the lucky ones that have ISP that fully supports IPv6, those might be lucky.  Per best practices ISP are to allocate a /48 (64k IPs from what I recall).  The end user could provide the application the range of IPv6s that can be used for source addresses.  That can help be more stealthy.

Do we want to go this way?

Is the web service answering?
yes) fasthttp or 1+ worker
no) stream random data/random packet size over tcp to endpoint:443 (requires root)

Is DNS answering?
yes) keep querying
no) stream non-stop random data/random packet size over udp to endpoint:53

If they have easy ways to block this application, is flooding the next step?

**Comment by deputinizer** [comment]
> Do we want to go this way?
Ok let's just flood :+1:

**Comment by deputinizer** [comment]
Turns out they are way better https://github.com/erkexzcx/stoppropaganda/pull/103

**Comment by deputinizer** [comment]
Turns out they are way better https://github.com/erkexzcx/stoppropaganda/pull/103
